version: '3.8'
services:
  postgres:
      image: postgres:14.1-alpine
      restart: always
      environment:
        POSTGRES_DB:       ${POSTGRES_HOST}:${POSTGRES_PORT}
        POSTGRES_USER:     ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - '5432:5432'
      volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local